TRUNCATE TABLE ps_product;
ALTER TABLE ps_product AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_attachment;
ALTER TABLE ps_product_attachment AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_country_tax;
ALTER TABLE ps_product_country_tax AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_group_reduction_cache;
ALTER TABLE ps_product_group_reduction_cache AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_lang;
ALTER TABLE ps_product_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_sale;
ALTER TABLE ps_product_sale AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_tag;
ALTER TABLE ps_product_tag AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_category_product;
ALTER TABLE ps_category_product AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_compare_product;
ALTER TABLE ps_compare_product AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_feature_product;
ALTER TABLE ps_feature_product AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_search_index;
ALTER TABLE ps_search_index AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_specific_price;
ALTER TABLE ps_specific_price AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_specific_price_priority;
ALTER TABLE ps_specific_price_priority AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_accessory;
ALTER TABLE ps_accessory AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_pack;
ALTER TABLE ps_pack AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attachment;
ALTER TABLE ps_attachment AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attachment_lang;
ALTER TABLE ps_attachment_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attribute;
ALTER TABLE ps_attribute AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attribute_lang;
ALTER TABLE ps_attribute_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attribute_group;
ALTER TABLE ps_attribute_group AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attribute_group_lang;
ALTER TABLE ps_attribute_group_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_attribute_impact;
ALTER TABLE ps_attribute_impact AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_feature;
ALTER TABLE ps_feature AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_feature_lang;
ALTER TABLE ps_feature_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_feature_value;
ALTER TABLE ps_feature_value AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_feature_value_lang;
ALTER TABLE ps_feature_value_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_customization_field;
ALTER TABLE ps_customization_field AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_customization_field_lang;
ALTER TABLE ps_customization_field_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_image;
ALTER TABLE ps_image AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_image_lang;
ALTER TABLE ps_image_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_attribute;
ALTER TABLE ps_product_attribute AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_attribute_combination;
ALTER TABLE ps_product_attribute_combination AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_attribute_image;
ALTER TABLE ps_product_attribute_image AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_product_download;
ALTER TABLE ps_product_download AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_search_word;
ALTER TABLE ps_search_word AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_cart;
ALTER TABLE ps_cart AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_cart_discount;
ALTER TABLE ps_cart_discount AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_cart_product;
ALTER TABLE ps_cart_product AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_customization;
ALTER TABLE ps_customization AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_customized_data;
ALTER TABLE ps_customized_data AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_scene;
ALTER TABLE ps_scene AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_scene_category;
ALTER TABLE ps_scene_category AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_scene_lang;
ALTER TABLE ps_scene_lang AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_scene_products;
ALTER TABLE ps_scene_products AUTO_INCREMENT = 1;
TRUNCATE TABLE ps_stock_mvt;
ALTER TABLE ps_stock_mvt AUTO_INCREMENT = 1;
